// <auto-generated />
using System;
using FabrikaHR.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FabrikaHR.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FabrikaHR.Models.Concrate.Avans", b =>
                {
                    b.Property<int>("AvansID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CevaplanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OnayDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParaBirimi")
                        .HasColumnType("int");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TalepTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TalepTutari")
                        .HasColumnType("float");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AvansID");

                    b.HasIndex("UserID");

                    b.ToTable("Avanses");
                });

            modelBuilder.Entity("FabrikaHR.Models.Concrate.Harcama", b =>
                {
                    b.Property<int>("HarcamaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CevaplanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("EkDosya")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("HarcamaTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HarcamaTutari")
                        .HasColumnType("float");

                    b.Property<string>("OnayDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParaBirimi")
                        .HasColumnType("int");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("HarcamaID");

                    b.HasIndex("UserID");

                    b.ToTable("Harcamas");
                });

            modelBuilder.Entity("FabrikaHR.Models.Concrate.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalismaStatusu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DogumTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DogumYeri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Fotograf")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Iletisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FabrikaHR.Models.Concrate.Avans", b =>
                {
                    b.HasOne("FabrikaHR.Models.Concrate.User", "User")
                        .WithMany("Avanses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FabrikaHR.Models.Concrate.Harcama", b =>
                {
                    b.HasOne("FabrikaHR.Models.Concrate.User", "User")
                        .WithMany("Harcamas")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FabrikaHR.Models.Concrate.User", b =>
                {
                    b.Navigation("Avanses");

                    b.Navigation("Harcamas");
                });
#pragma warning restore 612, 618
        }
    }
}
